version: '3.7'

services:
  zero9-server:
    container_name: zero9-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/zero9/src
    ports:
      - 3000:3000
      - 5000:3000
    env_file:
      - ./.env.docker
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - zero9-db

  zero9-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'zero9'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  zero9-redis:
    image: redis:alpine
    container_name: zero9-redis

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  logstash:
    image: logstash:7.17.0
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
      - ./elk/logstash/creator_template.json:/usr/share/logstash/creator_template.json
      - ./elk/logstash/product_template.json:/usr/share/logstash/product_template.json
