version: '3.7'

services:
  zero9-server:
    build:
      context: .
      dockerfile: Dockerfile.local
    platform: linux/arm64/v8
    container_name: zero9-server
    restart: always
    volumes:
      - ./src:/zero9/src
    ports:
      - 5050:3000
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - zero9-network

  zero9-redis:
    image: redis:alpine
    container_name: zero9-redis
    restart: always
    volumes:
      - zero9-redis:/data
    networks:
      - zero9-network

networks:
  zero9-network:
    driver: bridge

volumes:
  zero9-redis:
